# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lov7qX27Ugfyf9YirgM0HHxvz5wxikVL
"""

import json
import random
import pickle

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

# Load data
with open("intents.json", "r") as f:
    data = json.load(f)

patterns = []
tags = []

for intent in data["intents"]:
    for pattern in intent["patterns"]:
        patterns.append(pattern)
        tags.append(intent["tag"])

# Vectorize text → TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(patterns)

# Encode labels
le = LabelEncoder()
y = le.fit_transform(tags)

# Train model
model = LogisticRegression()
model.fit(X, y)

# Save model + vectorizer + label encoder
with open("model.pkl", "wb") as f:
    pickle.dump({
        "model": model,
        "vectorizer": vectorizer,
        "label_encoder": le,
        "intents": data
    }, f)
print("Model trained and saved as model.pkl")

